export const RouteNames = {
  CURRENT_UNIT_SCREEN: 'CurrentUnit',
  REJECT_UNIT_SCREEN: 'RejectUnit',
  PLANNED_UNIT_SCREEN: 'PlannedUnit',
  PLANNED_STACK_SCREEN: 'PlannedStack',
  PROFILE_STACK_SCREEN: 'ProfileStack',
  TRANSPORT_STACK_SCREEN: 'TransportStack',
  TRANSPORT_SCREEN: 'TransportScreen',
  CURRENT_UNIT_STACK_SCREEN: 'CurrentUnitStack',
  USER_ACTIONS_SCREEN: 'UserActions',
  SPLASH_SCREEN: 'SplashScreen',
  HOME_SCREEN: 'HomeScreen',
  LOGIN_SCREEN: 'LoginScreen',
  UNIT_DETAILS_SCREEN: 'UnitDetails',
  CONFIRM_CHANGES_SCREEN: 'ConfirmChanges',
  REJECT_CONFIRM_CHANGES_SCREEN: 'RejectConfirmChanges',
  ACTIVITY_LOG_SCREEN: 'ActivityLog',
  BREAK_TIME_SCREEN: 'BreakTime',
  CHANGE_PASSWORD_SCREEN: 'ChangePassword',
  NOTIFICATION_SCREEN: 'Notifications',
  ABORT_TRANSPORT_SCREEN: 'AbortTransport',
};
