export const ActionConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',

  TRANSPORT_REQUEST: 'TRANSPORT_REQUEST',
  TRANSPORT_ERROR: 'TRANSPORT_ERROR',
  TRANSPORT_SUCCESS: 'TRANSPORT_SUCCESS',
  SOCKET_TRANSPORT_REQUEST: 'SOCKET_TRANSPORT_REQUEST',

  PROFILE_REQUEST: 'PROFILE_REQUEST',
  PROFILE_ERROR: 'PROFILE_ERROR',
  PROFILE_SUCCESS: 'PROFILE_SUCCESS',

  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_ERROR: 'CHANGE_PASSWORD_ERROR',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',

  PLANNING_REQUEST: 'PLANNING_REQUEST',
  PLANNING_SUCCESS: 'PLANNING_SUCCESS',
  PLANNING_ERROR: 'PLANNING_ERROR',

  CURRENT_UNIT_REQUEST: 'CURRENT_UNIT_REQUEST',
  CURRENT_UNIT_SUCCESS: 'CURRENT_UNIT_SUCCESS',
  CURRENT_UNIT_ERROR: 'CURRENT_UNIT_ERROR',

  ACTIVITY_LOGS_REQUEST: 'ACTIVITY_LOGS_REQUEST',
  ACTIVITY_LOGS_SUCCESS: 'ACTIVITY_LOGS_SUCCESS',
  ACTIVITY_LOGS_ERROR: 'ACTIVITY_LOGS_ERROR',
  ACTIVITY_LOGS_FLUSH: 'ACTIVITY_LOGS_FLUSH',

  LANGUAGE_SUCCESS: 'LANGUAGE_SUCCESS',
  LANGUAGE_ERROR: 'LANGUAGE_ERROR',

  LOCATION_SUCCESS: 'LOCATION_SUCCESS',
  LOCATION_ERROR: 'LOCATION_ERROR',

  RESET_STORE: 'RESET_STORE',
};
